plugins {
    id 'java'
    id 'idea'
    id 'groovy'
    id 'jacoco'
}

repositories {
    mavenLocal()
    mavenCentral()
}

description = "Getting Groovy with Spock"
group mavenGroup
version projVersionNumber

sourceCompatibility = 21
targetCompatibility = 21

dependencies {
    testImplementation "net.bytebuddy:byte-buddy:1.15.10"
    testImplementation "org.spockframework:spock-core:2.3-groovy-4.0"
    testImplementation "org.apache.groovy:groovy:4.0.27"
}

test {
    useJUnitPlatform()
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
}
jacocoTestReport {
    reports {
        xml.required = true
    }
}
